spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weather?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations: 'filesystem:../resources/main/db.migration'
    check-location: false
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect