spring:
  datasource:
    url: jdbc:mysql://172.16.0.7:3306/weather?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: kfvchlb
    driver-class-name: com.mysql.jdbc.Driver
  flyway:
    locations: 'filesystem:../resources/main/db.migration'
    check-location: false
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect